### ISSUE TITLE
编译运行步骤

### ISSUE THREAD

**Issue by yangyuke001** [lenLRX/Atlas200DK_ACL#4]
请问，此工程的编译可以在20.1环境下进行吗？
如果可以，具体的build流程方便介绍一下吗？

**Comment by lenLRX** [comment]
可以，大体流程是一样的，区别是地方有标注，请阅读文档

**Comment by yangyuke001** [comment]
另外问下这个步骤：
运行测试(RTSP输入RTMP输出)
其中的第二小步，命令：
nohup vlc -v ... 是什么作用？
我这一步没执行，直接运行 ./run.sh 
会报错：Connection to tcp://192.168.x.x:1935?timeout=0 failed: Connection refused.
如果我执行命令：
nohup vlc -v ...
又报错：failed to run command 'vlc': No such file or directory
总的来说，没太明白  运行测试RTSP输入  这个流程。
期待答疑，感谢感谢

**Comment by yangyuke001** [comment]
谢谢你，跑起来了已经
