### ISSUE TITLE
运行例程失败 no libraries: libacl_demo.so

### ISSUE THREAD

**Issue by WinstonLy** [lenLRX/Atlas200DK_ACL#5]
编译成功之后运行run.sh的时候出现以下问题：
./build/acl_multi_stream_demo: error while loading shared libraries: libacl_demo.so: cannot open shared object file: No such file or directory
请问是什么原因呢？

**Comment by lenLRX** [comment]
看一下./build/libacl_demo.so 这个文件是否存在。
如果存在的话试着把build目录加到LD_LIBRARY_PATH中再试试。

**Comment by WinstonLy** [comment]
好的，按照你提供的意见已经解决
