### ISSUE TITLE
memcpy(input_buffers[0], buffer, model->GetInputBufferSizes()[0]);报错问题

### ISSUE THREAD

**Issue by 120888389** [lenLRX/Atlas200DK_ACL#6]
![1](https://user-images.githubusercontent.com/67918019/105440231-309cbb00-5ca1-11eb-9328-947427cfc316.png)
![2](https://user-images.githubusercontent.com/67918019/105440246-34304200-5ca1-11eb-851d-7e47370c9af0.png)
您好，首先感谢仓主的分享，当时我在实际运行中发现了这个问题，麻烦仓主关注一下这个问题（图一为运行报错，图二为GDB调试结果）
万分感谢！

**Comment by lenLRX** [comment]
最开始的报错信息来看，很大概率是你没有正确的转换模型并且放到指定位置

**Comment by 120888389** [comment]
这边方便加您一个联系方式么，想请教您一些操作问题

**Comment by lenLRX** [comment]
> 这边方便加您一个联系方式么，想请教您一些操作问题

就直接提在这里吧，以后别人也能看到

**Comment by 120888389** [comment]
![1](https://user-images.githubusercontent.com/67918019/105457294-85e8c480-5cc1-11eb-8203-22a753db458e.png)
![2](https://user-images.githubusercontent.com/67918019/105457298-897c4b80-5cc1-11eb-8659-f885fcd5e07d.png)
![3](https://user-images.githubusercontent.com/67918019/105457301-8b460f00-5cc1-11eb-9fb7-c42784a95a0f.png)

目前是打开yolov3的模型文件出现以下问题

**Comment by lenLRX** [comment]
> ![1](https://user-images.githubusercontent.com/67918019/105457294-85e8c480-5cc1-11eb-8203-22a753db458e.png)
> ![2](https://user-images.githubusercontent.com/67918019/105457298-897c4b80-5cc1-11eb-8659-f885fcd5e07d.png)
> ![3](https://user-images.githubusercontent.com/67918019/105457301-8b460f00-5cc1-11eb-9fb7-c42784a95a0f.png)
> 
> 目前是打开yolov3的模型文件出现以下问题

请参考我在readme里面写的模型转换章节的文档操作，不需要mindstudio

**Comment by 120888389** [comment]
目前是全部按照您的操作走，依旧出现段错误
操作流程：1、虚拟机中下载yolov3的模型文件与您的代码，提取yolov3的模型文件yolov3.caffemodel文件到您的代码中的model文件夹中
                  2、虚拟机中执行atc --model=yolov3_pp.prototxt --weight=yolov3.caffemodel --framework=0 --output=sample-yolov3_pp_416 --soc_version=Ascend310 --insert_op_conf=./aipp_yolov3_pp.cfg
                  3、在开发板中下载您的代码
                  4、将虚拟机中得到的sample-yolov3_pp_416.om拷贝到开发板中的model文件夹中
                   5、执行命令

**Comment by lenLRX** [comment]
> 目前是全部按照您的操作走，依旧出现段错误
> 操作流程：1、虚拟机中下载yolov3的模型文件与您的代码，提取yolov3的模型文件yolov3.caffemodel文件到您的代码中的model文件夹中
>                   2、虚拟机中执行atc --model=yolov3_pp.prototxt --weight=yolov3.caffemodel --framework=0 --output=sample-yolov3_pp_416 --soc_version=Ascend310 --insert_op_conf=./aipp_yolov3_pp.cfg
>                   3、在开发板中下载您的代码
>                   4、将虚拟机中得到的sample-yolov3_pp_416.om拷贝到开发板中的model文件夹中
>                    5、执行命令

麻烦你再发一下最新的命令行截图看看

**Comment by 120888389** [comment]
![1](https://user-images.githubusercontent.com/67918019/105466448-33aea000-5ccf-11eb-8676-370edc034106.png)
您看一下

**Comment by lenLRX** [comment]
> ![1](https://user-images.githubusercontent.com/67918019/105466448-33aea000-5ccf-11eb-8676-370edc034106.png)
> 您看一下
> 

我的命令都假设是在仓库根目录执行的，你现在是在build文件夹执行的。所以. /model/找不到对应的文件。

你试试在仓库根目录执行. /build/acl_xxx j加你原来的目录试试

**Comment by 120888389** [comment]
好用了好用了，非常抱歉是我的问题浪费了您这么多的宝贵时间，在这里表示深深的歉意，非常感谢您的帮助，祝您生活愉快！

**Comment by 120888389** [comment]
![1](https://user-images.githubusercontent.com/67918019/105469029-a2412d00-5cd2-11eb-97c8-3f4078dbb484.png)
![2](https://user-images.githubusercontent.com/67918019/105469033-a2d9c380-5cd2-11eb-83ef-2dd079b532a4.png)
![3](https://user-images.githubusercontent.com/67918019/105469037-a4a38700-5cd2-11eb-8c60-e9bce40e1f61.png)
![4](https://user-images.githubusercontent.com/67918019/105469046-a66d4a80-5cd2-11eb-9909-d07721799163.png)
请问一下这个推流功能中的nginx服务器nginx.conf配置出现错误了

**Comment by lenLRX** [comment]
> ![1](https://user-images.githubusercontent.com/67918019/105469029-a2412d00-5cd2-11eb-97c8-3f4078dbb484.png)
> ![2](https://user-images.githubusercontent.com/67918019/105469033-a2d9c380-5cd2-11eb-83ef-2dd079b532a4.png)
> ![3](https://user-images.githubusercontent.com/67918019/105469037-a4a38700-5cd2-11eb-8c60-e9bce40e1f61.png)
> ![4](https://user-images.githubusercontent.com/67918019/105469046-a66d4a80-5cd2-11eb-9909-d07721799163.png)
> 请问一下这个推流功能中的nginx服务器nginx.conf配置出现错误了

这个nginx似乎不支持rtsp，只支持rtmp。
另外推流地址一定要满足ip/myapp/streamxxx这样的格式，重点是myapp

**Comment by 120888389** [comment]
![1](https://user-images.githubusercontent.com/67918019/105473790-79239b00-5cd8-11eb-9d51-656169049284.png)
![2](https://user-images.githubusercontent.com/67918019/105473791-79bc3180-5cd8-11eb-822a-84ba5214046e.jpg)
![3](https://user-images.githubusercontent.com/67918019/105473796-7aed5e80-5cd8-11eb-8dbe-c7d5f8cc3e1c.png)
![4](https://user-images.githubusercontent.com/67918019/105473805-7c1e8b80-5cd8-11eb-9132-0636a258ebb8.png)
非常抱歉，我这边实际操作摄像头作为输入出现了问题，还得麻烦您帮忙看一下，可能是那块出现了问题

**Comment by lenLRX** [comment]
这我就不清楚了，之前你跑其他程序的时候摄像头是正常的吗？
可以试试重启设备，记得启动nginx, nginx开机不会自动重启

**Comment by 120888389** [comment]
摄像头功能是正常的
跑过摄像头样例验证我的摄像头型号是支持的https://gitee.com/ascend/samples/tree/master/cplusplus/level1_single_api/5_200dk_peripheral/ascendcamera

**Comment by lenLRX** [comment]
> 摄像头功能是正常的
> 跑过摄像头样例验证我的摄像头型号是支持的https://gitee.com/ascend/samples/tree/master/cplusplus/level1_single_api/5_200dk_peripheral/ascendcamera

之前的代码对于camera1的处理有点问题，请你拉取最新代码重新测试一下。

测试前请将其他占用摄像头的程序关掉，两个摄像头都测试一下试试

**Comment by 120888389** [comment]
![Snipaste_2021-01-27_09-17-17](https://user-images.githubusercontent.com/67918019/105928218-7d590b00-6080-11eb-999f-3b5b8526741f.png)
目前已经拉取最新的代码，但是还是有问题，两个摄像头为同一型号，均支持样例拍照

**Comment by lenLRX** [comment]
> ![Snipaste_2021-01-27_09-17-17](https://user-images.githubusercontent.com/67918019/105928218-7d590b00-6080-11eb-999f-3b5b8526741f.png)
> 目前已经拉取最新的代码，但是还是有问题，两个摄像头为同一型号，均支持样例拍照

很好，这个报错是FPS不支持。
你把这个代码里面的FPS调低一点，比如5或10，应该就行了

https://github.com/lenLRX/Atlas200DK_ACL/blob/ced5ba503f38527a8508cb33f19c0c1b07b9c0f5/src/camera_input.cpp#L68

**Comment by lenLRX** [comment]
我先关了这个issue，如果还有问题请开新的issue
